spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_admin_platform?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

debug: true
